import Link from 'next/link';
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, HTMLAttributes, ReactNode } from 'react';
import { initials } from '@/lib/format';

/* ==========================================================================
   Primitives
   --------------------------------------------------------------------------
   Everything the interface is built from. Variants exist because they mean
   something, not to offer choice: `primary` is the one action on a screen,
   `impact` is reserved for contributions, and `ghost` is for everything that
   should not compete.
   ========================================================================== */

export function cx(...values: (string | false | null | undefined)[]): string {
  return values.filter(Boolean).join(' ');
}

/* ------------------------------- Button ---------------------------------- */

type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'impact' | 'danger' | 'inverted';
type ButtonSize = 'sm' | 'md' | 'lg';

const BUTTON_BASE =
  'inline-flex items-center justify-center gap-2 font-semibold rounded-[--radius-field] transition-all duration-200 ' +
  'disabled:opacity-45 disabled:pointer-events-none select-none whitespace-nowrap';

const BUTTON_VARIANTS: Record<ButtonVariant, string> = {
  primary: 'bg-ink text-white hover:bg-ink-soft active:scale-[0.985] shadow-[0_1px_2px_rgba(14,17,19,0.16)]',
  secondary: 'bg-white text-ink border border-line-strong hover:border-ink hover:bg-sand active:scale-[0.985]',
  ghost: 'text-ink-soft hover:text-ink hover:bg-sand',
  impact: 'bg-clay-500 text-white hover:bg-clay-600 active:scale-[0.985]',
  danger: 'bg-white text-danger border border-danger/25 hover:bg-danger-soft',
  inverted: 'bg-white text-ink hover:bg-white/90 active:scale-[0.985]',
};

// Touch targets stay at 44px and up on the smallest size — this is a phone-first
// product and buttons get tapped with thumbs.
const BUTTON_SIZES: Record<ButtonSize, string> = {
  sm: 'h-10 px-4 text-[0.8125rem]',
  md: 'h-12 px-6 text-sm',
  lg: 'h-14 px-8 text-[0.9375rem]',
};

interface ButtonBaseProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
  full?: boolean;
  className?: string;
  children: ReactNode;
}

export function Button({
  variant = 'primary',
  size = 'md',
  full,
  className,
  children,
  ...props
}: ButtonBaseProps & ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      className={cx(BUTTON_BASE, BUTTON_VARIANTS[variant], BUTTON_SIZES[size], full && 'w-full', className)}
      {...props}
    >
      {children}
    </button>
  );
}

export function ButtonLink({
  variant = 'primary',
  size = 'md',
  full,
  className,
  href,
  children,
  ...props
}: ButtonBaseProps & { href: string } & Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'href'>) {
  return (
    <Link
      href={href}
      className={cx(BUTTON_BASE, BUTTON_VARIANTS[variant], BUTTON_SIZES[size], full && 'w-full', className)}
      {...props}
    >
      {children}
    </Link>
  );
}

/* -------------------------------- Card ----------------------------------- */

export function Card({
  className,
  children,
  as: Tag = 'div',
}: {
  className?: string;
  children: ReactNode;
  as?: 'div' | 'article' | 'section' | 'li';
}) {
  return (
    <Tag className={cx('rounded-[--radius-card] border border-line bg-white', className)}>{children}</Tag>
  );
}

/* ------------------------------- Badge ----------------------------------- */

type BadgeTone = 'neutral' | 'brand' | 'impact' | 'success' | 'warning' | 'danger' | 'dark';

const BADGE_TONES: Record<BadgeTone, string> = {
  neutral: 'bg-sand text-ink-soft border-line',
  brand: 'bg-acacia-50 text-acacia-700 border-acacia-100',
  impact: 'bg-clay-50 text-clay-700 border-clay-100',
  success: 'bg-acacia-50 text-acacia-700 border-acacia-100',
  warning: 'bg-[#fdf4e3] text-warning border-[#f2e2c0]',
  danger: 'bg-danger-soft text-danger border-danger/15',
  dark: 'bg-ink text-white border-ink',
};

export function Badge({
  tone = 'neutral',
  children,
  className,
}: {
  tone?: BadgeTone;
  children: ReactNode;
  className?: string;
}) {
  return (
    <span
      className={cx(
        'inline-flex items-center gap-1.5 rounded-[--radius-pill] border px-2.5 py-1 text-[0.6875rem] font-semibold tracking-wide',
        BADGE_TONES[tone],
        className,
      )}
    >
      {children}
    </span>
  );
}

/**
 * Marks content that was generated by the demonstration seed.
 *
 * This exists so figures on screen are never mistaken for real results. It is
 * used wherever seeded numbers appear, and it should stay until real data does.
 */
export function DemoBadge({ className, label = 'Demo data' }: { className?: string; label?: string }) {
  return (
    <span
      className={cx(
        'inline-flex items-center gap-1.5 rounded-[--radius-pill] border border-dashed border-line-strong bg-white/80 px-2.5 py-1 text-[0.625rem] font-semibold uppercase tracking-[0.12em] text-ink-muted backdrop-blur',
        className,
      )}
      title="Demonstration content. Not a record of real activity."
    >
      <span className="h-1.5 w-1.5 rounded-full bg-ink-faint" />
      {label}
    </span>
  );
}

/* ------------------------------- Eyebrow --------------------------------- */

export function Eyebrow({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <p className={cx('text-eyebrow uppercase text-ink-muted', className)}>{children}</p>
  );
}

/* ------------------------------ Section head ----------------------------- */

export function SectionHead({
  eyebrow,
  title,
  description,
  action,
  className,
  align = 'left',
}: {
  eyebrow?: string;
  title: ReactNode;
  description?: ReactNode;
  action?: ReactNode;
  className?: string;
  align?: 'left' | 'center';
}) {
  return (
    <div
      className={cx(
        'flex flex-col gap-5 md:flex-row md:items-end md:justify-between',
        align === 'center' && 'md:flex-col md:items-center md:text-center',
        className,
      )}
    >
      <div className={cx('max-w-2xl', align === 'center' && 'mx-auto')}>
        {eyebrow && <Eyebrow className="mb-3">{eyebrow}</Eyebrow>}
        <h2 className="text-h2 text-balance">{title}</h2>
        {description && <p className="mt-3 text-[0.9375rem] leading-relaxed text-ink-muted">{description}</p>}
      </div>
      {action && <div className="shrink-0">{action}</div>}
    </div>
  );
}

/* ------------------------------- Progress -------------------------------- */

/**
 * A funding meter. The number is always written next to the bar — a bar alone
 * asks the reader to estimate, and with money that is not good enough.
 */
export function Progress({
  percent,
  tone = 'impact',
  size = 'md',
  className,
  label,
}: {
  percent: number;
  tone?: 'impact' | 'brand' | 'neutral';
  size?: 'sm' | 'md';
  className?: string;
  label?: string;
}) {
  const clamped = Math.max(0, Math.min(100, Math.round(percent)));
  const fill =
    tone === 'impact' ? 'bg-clay-500' : tone === 'brand' ? 'bg-acacia-600' : 'bg-ink';

  return (
    <div
      className={cx('w-full', className)}
      role="progressbar"
      aria-valuenow={clamped}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-label={label ?? `${clamped}% funded`}
    >
      <div className={cx('w-full overflow-hidden rounded-full bg-sand-deep', size === 'sm' ? 'h-1.5' : 'h-2')}>
        <div
          className={cx('h-full rounded-full transition-[width] duration-700', fill)}
          style={{ width: `${clamped}%` }}
        />
      </div>
    </div>
  );
}

/* -------------------------------- Avatar --------------------------------- */

/**
 * Initial-based avatars.
 *
 * Demo accounts deliberately have no photograph — using stock portraits of real
 * people as stand-ins for fictional travellers misrepresents them. The tint is
 * derived from the name so a person keeps the same colour everywhere.
 */
const AVATAR_TINTS = [
  'bg-acacia-100 text-acacia-700',
  'bg-clay-100 text-clay-700',
  'bg-sand-deep text-ink-soft',
  'bg-[#e3e9ef] text-[#2f4a63]',
  'bg-[#eae4f0] text-[#4d3c63]',
];

function tintFor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i += 1) hash = (hash * 31 + name.charCodeAt(i)) % 997;
  return AVATAR_TINTS[hash % AVATAR_TINTS.length];
}

const AVATAR_SIZES = {
  xs: 'h-7 w-7 text-[0.625rem]',
  sm: 'h-9 w-9 text-[0.6875rem]',
  md: 'h-11 w-11 text-xs',
  lg: 'h-16 w-16 text-base',
  xl: 'h-24 w-24 text-2xl',
} as const;

export function Avatar({
  name,
  src,
  size = 'md',
  className,
  ring,
}: {
  name: string;
  src?: string | null;
  size?: keyof typeof AVATAR_SIZES;
  className?: string;
  ring?: boolean;
}) {
  const classes = cx(
    'inline-flex shrink-0 items-center justify-center rounded-full font-bold tracking-wide overflow-hidden',
    AVATAR_SIZES[size],
    ring && 'ring-2 ring-white',
    className,
  );

  if (src) {
    // eslint-disable-next-line @next/next/no-img-element
    return <img src={src} alt={name} className={cx(classes, 'object-cover')} />;
  }

  return (
    <span className={cx(classes, tintFor(name))} aria-label={name} title={name}>
      {initials(name)}
    </span>
  );
}

/** Overlapping avatars for "who else is coming". */
export function AvatarStack({
  people,
  max = 5,
  size = 'sm',
}: {
  people: { id: string; name: string; avatarUrl?: string | null }[];
  max?: number;
  size?: keyof typeof AVATAR_SIZES;
}) {
  const shown = people.slice(0, max);
  const remaining = people.length - shown.length;

  return (
    <div className="flex items-center">
      <div className="flex -space-x-2.5">
        {shown.map((person) => (
          <Avatar key={person.id} name={person.name} src={person.avatarUrl} size={size} ring />
        ))}
      </div>
      {remaining > 0 && (
        <span className="ml-3 text-[0.8125rem] font-medium text-ink-muted">+{remaining} more</span>
      )}
    </div>
  );
}

/* -------------------------------- Rating --------------------------------- */

export function Stars({ rating, size = 14 }: { rating: number; size?: number }) {
  return (
    <span className="inline-flex items-center gap-0.5" aria-label={`${rating} out of 5`}>
      {[1, 2, 3, 4, 5].map((index) => (
        <svg
          key={index}
          width={size}
          height={size}
          viewBox="0 0 20 20"
          aria-hidden="true"
          className={index <= Math.round(rating) ? 'text-clay-500' : 'text-line-strong'}
          fill="currentColor"
        >
          <path d="M10 1.5l2.47 5.36 5.78.66-4.3 3.96 1.16 5.77L10 14.4l-5.11 2.85 1.16-5.77-4.3-3.96 5.78-.66z" />
        </svg>
      ))}
    </span>
  );
}

export function RatingLine({
  rating,
  count,
  className,
}: {
  rating: number | null;
  count: number;
  className?: string;
}) {
  if (rating === null || count === 0) {
    return <span className={cx('text-[0.8125rem] text-ink-faint', className)}>No reviews yet</span>;
  }
  return (
    <span className={cx('inline-flex items-center gap-1.5 text-[0.8125rem]', className)}>
      <svg width="14" height="14" viewBox="0 0 20 20" fill="currentColor" className="text-clay-500">
        <path d="M10 1.5l2.47 5.36 5.78.66-4.3 3.96 1.16 5.77L10 14.4l-5.11 2.85 1.16-5.77-4.3-3.96 5.78-.66z" />
      </svg>
      <span className="font-semibold text-ink">{rating.toFixed(1)}</span>
      <span className="text-ink-muted">({count})</span>
    </span>
  );
}

/* ------------------------------ Verification ----------------------------- */

/**
 * The verified-operator badge.
 *
 * Only rendered for `VERIFIED`, which the API only sets after an admin decision.
 * Demonstration operators carry a note saying so, because a badge that appears
 * without a real check is worse than no badge.
 */
export function VerifiedBadge({ isDemo, className }: { isDemo?: boolean; className?: string }) {
  return (
    <span
      className={cx('inline-flex items-center gap-1.5 text-[0.75rem] font-semibold text-acacia-700', className)}
      title={
        isDemo
          ? 'Demonstration operator. No real verification was performed on this account.'
          : 'Verified by the Enhakkore team.'
      }
    >
      <svg width="15" height="15" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path d="M10 1l2.2 1.6 2.7-.2.9 2.6 2.2 1.6-1 2.5 1 2.5-2.2 1.6-.9 2.6-2.7-.2L10 19l-2.2-1.6-2.7.2-.9-2.6L2 13.4l1-2.5-1-2.5 2.2-1.6.9-2.6 2.7.2z" />
        <path d="M8.8 12.6L6.3 10l1.1-1.1 1.4 1.4 3.8-3.8 1.1 1.1z" fill="#fff" />
      </svg>
      Verified operator
      {isDemo && <span className="font-medium text-ink-faint">· demo</span>}
    </span>
  );
}

/* ------------------------------ Stat tile -------------------------------- */

export function StatTile({
  label,
  value,
  hint,
  tone = 'neutral',
  className,
}: {
  label: string;
  value: ReactNode;
  hint?: ReactNode;
  tone?: 'neutral' | 'impact' | 'brand';
  className?: string;
}) {
  const valueTone = tone === 'impact' ? 'text-clay-600' : tone === 'brand' ? 'text-acacia-700' : 'text-ink';
  return (
    <div className={cx('rounded-[--radius-card] border border-line bg-white p-5 md:p-6', className)}>
      <p className="text-eyebrow uppercase text-ink-muted">{label}</p>
      <p className={cx('mt-3 text-[1.75rem] font-bold leading-none tracking-tight md:text-[2rem]', valueTone)}>
        {value}
      </p>
      {hint && <p className="mt-2 text-[0.8125rem] leading-snug text-ink-muted">{hint}</p>}
    </div>
  );
}

/* ------------------------------ Empty state ------------------------------ */

/**
 * Empty states say what happened and what to do next. Never just "no results".
 */
export function EmptyState({
  title,
  description,
  action,
  icon,
  className,
}: {
  title: string;
  description?: ReactNode;
  action?: ReactNode;
  icon?: ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cx(
        'flex flex-col items-center justify-center rounded-[--radius-card] border border-dashed border-line-strong bg-sand/40 px-6 py-16 text-center',
        className,
      )}
    >
      {icon && <div className="mb-5 text-ink-faint">{icon}</div>}
      <h3 className="text-h3">{title}</h3>
      {description && <p className="mt-2 max-w-md text-[0.9375rem] leading-relaxed text-ink-muted">{description}</p>}
      {action && <div className="mt-7">{action}</div>}
    </div>
  );
}

/* -------------------------------- Skeleton -------------------------------- */

export function Skeleton({ className }: { className?: string }) {
  return <div className={cx('animate-pulse rounded-[--radius-field] bg-sand-deep', className)} />;
}

export function TripCardSkeleton() {
  return (
    <div className="rounded-[--radius-card] border border-line bg-white p-3">
      <Skeleton className="aspect-[4/3] w-full rounded-[0.75rem]" />
      <div className="space-y-2.5 p-3">
        <Skeleton className="h-3 w-24" />
        <Skeleton className="h-5 w-3/4" />
        <Skeleton className="h-3 w-1/2" />
        <Skeleton className="h-px w-full" />
        <Skeleton className="h-5 w-1/3" />
      </div>
    </div>
  );
}

/* --------------------------------- Alert ---------------------------------- */

export function Alert({
  tone = 'neutral',
  title,
  children,
  className,
  ...props
}: {
  tone?: 'neutral' | 'danger' | 'success' | 'info';
  title?: string;
  children: ReactNode;
  className?: string;
} & HTMLAttributes<HTMLDivElement>) {
  const tones = {
    neutral: 'border-line bg-sand text-ink-soft',
    danger: 'border-danger/20 bg-danger-soft text-danger',
    success: 'border-acacia-100 bg-acacia-50 text-acacia-700',
    info: 'border-line bg-white text-ink-soft',
  };
  return (
    <div
      className={cx('rounded-[--radius-field] border px-4 py-3.5 text-[0.875rem] leading-relaxed', tones[tone], className)}
      {...props}
    >
      {title && <p className="mb-1 font-semibold">{title}</p>}
      {children}
    </div>
  );
}

/* --------------------------------- Divider -------------------------------- */

export function Divider({ className }: { className?: string }) {
  return <hr className={cx('border-0 border-t border-line', className)} />;
}

/* ------------------------------- Icons ------------------------------------ */

/** A small, consistent icon set. Stroke-based, 1.6px, 24px grid. */
export const Icon = {
  arrow: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M5 12h14M13 6l6 6-6 6" />
    </svg>
  ),
  search: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 18}
      height={props.size ?? 18}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.9"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="11" cy="11" r="7" />
      <path d="M20 20l-3.5-3.5" />
    </svg>
  ),
  pin: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M12 21s7-5.5 7-11a7 7 0 10-14 0c0 5.5 7 11 7 11z" />
      <circle cx="12" cy="10" r="2.5" />
    </svg>
  ),
  calendar: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <rect x="3" y="5" width="18" height="16" rx="2.5" />
      <path d="M3 10h18M8 3v4M16 3v4" />
    </svg>
  ),
  users: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="9" cy="8" r="3.2" />
      <path d="M2.5 20a6.5 6.5 0 0113 0M16 5.2a3.2 3.2 0 010 5.9M18 20a6 6 0 00-2-4.4" />
    </svg>
  ),
  clock: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M12 7v5.2l3.2 2" />
    </svg>
  ),
  chat: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M21 12a8 8 0 01-11.6 7.1L3 21l1.9-6.4A8 8 0 1121 12z" />
    </svg>
  ),
  heart: (props: { className?: string; size?: number; filled?: boolean }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill={props.filled ? 'currentColor' : 'none'}
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M12 20s-7-4.4-7-9.4A4.2 4.2 0 0112 7.6a4.2 4.2 0 017 3c0 5-7 9.4-7 9.4z" />
    </svg>
  ),
  check: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M4 12.5l5.2 5L20 7" />
    </svg>
  ),
  close: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 18}
      height={props.size ?? 18}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M6 6l12 12M18 6L6 18" />
    </svg>
  ),
  filter: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.9"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M4 6h16M7 12h10M10 18h4" />
    </svg>
  ),
  compass: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 20}
      height={props.size ?? 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M15.5 8.5l-2 5-5 2 2-5z" />
    </svg>
  ),
  home: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 20}
      height={props.size ?? 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M4 10.5L12 4l8 6.5V20a1 1 0 01-1 1h-4v-6H9v6H5a1 1 0 01-1-1z" />
    </svg>
  ),
  ticket: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 20}
      height={props.size ?? 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M3 8.5A2 2 0 015 6.5h14a2 2 0 012 2v1.2a2.3 2.3 0 000 4.6v1.2a2 2 0 01-2 2H5a2 2 0 01-2-2v-1.2a2.3 2.3 0 000-4.6z" />
      <path d="M14 6.5v11" strokeDasharray="2 2.4" />
    </svg>
  ),
  ripple: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 20}
      height={props.size ?? 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="2" fill="currentColor" stroke="none" />
      <path d="M6.5 12a5.5 5.5 0 015.5-5.5" opacity="0.6" />
      <path d="M17.5 12A5.5 5.5 0 0112 17.5" opacity="0.6" />
      <path d="M3 12A9 9 0 0112 3" opacity="0.35" />
      <path d="M21 12a9 9 0 01-9 9" opacity="0.35" />
    </svg>
  ),
  user: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 20}
      height={props.size ?? 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <circle cx="12" cy="8.5" r="3.6" />
      <path d="M4.5 20a7.5 7.5 0 0115 0" />
    </svg>
  ),
  plus: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 16}
      height={props.size ?? 16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M12 5v14M5 12h14" />
    </svg>
  ),
  shield: (props: { className?: string; size?: number }) => (
    <svg
      width={props.size ?? 18}
      height={props.size ?? 18}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinejoin="round"
      className={props.className}
      aria-hidden="true"
    >
      <path d="M12 3l7 2.8v5.4c0 4.4-3 8-7 9.8-4-1.8-7-5.4-7-9.8V5.8z" />
      <path d="M9 12l2 2 4-4" strokeLinecap="round" />
    </svg>
  ),
};
