import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import type { ImpactProjectSummary, Money, Paginated } from '@enhakkore/shared';
import { IMPACT_CATEGORIES, IMPACT_CATEGORY_LABELS } from '@enhakkore/shared';
import { PublicShell } from '@/components/layout/PublicShell';
import { ProjectCard } from '@/components/impact/ProjectCard';
import {
  ButtonLink,
  Card,
  DemoBadge,
  EmptyState,
  Eyebrow,
  Icon,
  SectionHead,
  cx,
} from '@/components/ui';
import { apiGet, query } from '@/lib/api';
import { price } from '@/lib/format';

export const metadata: Metadata = {
  title: 'Impact',
  description:
    'Support verified projects and see how your contribution creates meaningful change — goal, amount raised, and a dated record of what was done.',
};

export const revalidate = 120;

interface ImpactSummary {
  totalContributions: Money;
  contributionCount: number;
  travellersInvolved: number;
  projectsSupported: number;
  projectsCompleted: number;
  communitiesReached: number;
  countries: number;
  byCategory: Record<string, number>;
  isDemoData: boolean;
}

const PILLARS = [
  {
    title: 'A named project, not a pool',
    body: 'Every contribution goes to one project you can open, read and follow. There is no general fund that money disappears into.',
  },
  {
    title: 'The goal is public',
    body: 'Each project states what it costs and how much has been raised. The percentage you see is calculated from those two numbers, not written by hand.',
  },
  {
    title: 'Progress is dated',
    body: 'Updates carry a date and describe what actually happened — including the parts that went slower than planned.',
  },
  {
    title: 'No commission on contributions',
    body: 'Enhakkore earns from booking commission. Contributions pass through in full.',
  },
];

export default async function ImpactPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const category = typeof params.category === 'string' ? params.category : undefined;

  const [projects, summary] = await Promise.all([
    apiGet<Paginated<ImpactProjectSummary>>(`/impact/projects${query({ category, pageSize: 12 })}`),
    apiGet<ImpactSummary>('/impact/summary'),
  ]);

  const items = projects?.items ?? [];

  return (
    <PublicShell transparentHeader>
      {/* Hero */}
      <section className="relative flex min-h-[32rem] items-end overflow-hidden pb-14 pt-40">
        <Image
          src="https://images.unsplash.com/photo-1538300342682-cf57afb97285?auto=format&fit=crop&w=2400&h=1400&q=85"
          alt="Clean water running into open hands"
          fill
          priority
          sizes="100vw"
          className="object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-[#080a0b] via-[#080a0b]/60 to-[#080a0b]/30" />

        <div className="shell relative">
          <Eyebrow className="text-white/55">Impact</Eyebrow>
          <h1 className="mt-4 max-w-3xl text-[2.5rem] font-extrabold leading-[1.03] tracking-[-0.035em] text-white text-balance md:text-[3.75rem]">
            Travel can change more than you.
          </h1>
          <p className="mt-5 max-w-xl text-[1.0625rem] leading-relaxed text-white/78">
            Support projects with a stated goal, a public total and a dated record of what has been done —
            then follow what happens next.
          </p>
        </div>
      </section>

      {/* Numbers */}
      {summary && (
        <section className="border-b border-line bg-white">
          <div className="shell py-10 md:py-12">
            {summary.isDemoData && (
              <div className="mb-6 flex flex-wrap items-center gap-3">
                <DemoBadge label="Demonstration figures" />
                <p className="text-[0.8125rem] text-ink-muted">
                  Generated by the development seed. Not a record of money raised or work completed.
                </p>
              </div>
            )}

            <dl className="grid grid-cols-2 gap-8 md:grid-cols-4">
              {[
                { label: 'Total contributions', value: price(summary.totalContributions, true), tone: 'impact' },
                { label: 'Travellers involved', value: summary.travellersInvolved.toLocaleString('en-GB') },
                { label: 'Projects supported', value: summary.projectsSupported.toLocaleString('en-GB') },
                { label: 'Communities reached', value: summary.communitiesReached.toLocaleString('en-GB') },
              ].map((stat) => (
                <div key={stat.label}>
                  <dt className="text-eyebrow uppercase text-ink-muted">{stat.label}</dt>
                  <dd
                    className={cx(
                      'mt-2.5 text-[1.75rem] font-bold leading-none tracking-tight md:text-[2.25rem]',
                      stat.tone === 'impact' ? 'text-clay-600' : 'text-ink',
                    )}
                  >
                    {stat.value}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </section>
      )}

      {/* Projects */}
      <section className="section">
        <div className="shell">
          <SectionHead
            eyebrow="Projects"
            title="Where contributions go"
            description="Each project is run locally, with a committee or partner responsible for delivery on the ground."
          />

          {/* Category filter */}
          <div className="mt-8 flex gap-2 overflow-x-auto pb-1 no-scrollbar">
            <CategoryChip href="/impact" label="All projects" active={!category} />
            {IMPACT_CATEGORIES.map((item) => (
              <CategoryChip
                key={item}
                href={`/impact?category=${item}`}
                label={IMPACT_CATEGORY_LABELS[item]}
                active={category === item}
              />
            ))}
          </div>

          {items.length === 0 ? (
            <EmptyState
              className="mt-10"
              icon={<Icon.ripple size={34} />}
              title="No projects in this category yet"
              description="We publish a project only once it has a named location, a committee or partner responsible for it, and a costed plan. Try another category in the meantime."
              action={<ButtonLink href="/impact">See all projects</ButtonLink>}
            />
          ) : (
            <div className="mt-10 grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">
              {items.map((project, index) => (
                <ProjectCard key={project.id} project={project} priority={index < 3} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Trust */}
      <section className="section bg-sand">
        <div className="shell">
          <SectionHead
            eyebrow="How this works"
            title="Why you can check this rather than take our word for it"
            description="Charity asks for trust. The least a platform can do is make that trust checkable."
          />

          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {PILLARS.map((pillar, index) => (
              <Card key={pillar.title} className="p-6">
                <span className="text-[0.6875rem] font-bold tracking-[0.16em] text-clay-600">
                  {String(index + 1).padStart(2, '0')}
                </span>
                <h3 className="mt-3 text-[1rem] font-bold leading-snug tracking-tight">{pillar.title}</h3>
                <p className="mt-2 text-[0.875rem] leading-relaxed text-ink-muted">{pillar.body}</p>
              </Card>
            ))}
          </div>

          <Card className="mt-8 border-dashed p-6">
            <h3 className="text-[0.9375rem] font-bold tracking-tight">Where this build honestly stands</h3>
            <p className="mt-2 max-w-3xl text-[0.875rem] leading-relaxed text-ink-muted">
              The projects on this page are demonstration records created for development. No funds have
              been raised or disbursed, no implementing partner has been contracted, and no independent
              audit has taken place. The structure — goals, totals, allocation, dated updates — is real and
              is what live projects will be held to.
            </p>
          </Card>
        </div>
      </section>

      {/* CTA */}
      <section className="section-tight">
        <div className="shell">
          <Card className="overflow-hidden">
            <div className="grid lg:grid-cols-[1.2fr_1fr]">
              <div className="p-8 md:p-12">
                <Eyebrow className="text-clay-600">Travel with purpose</Eyebrow>
                <h2 className="mt-3 text-h2 text-balance">
                  The simplest way to give is on a trip you were taking anyway.
                </h2>
                <p className="mt-4 max-w-lg text-[0.9375rem] leading-relaxed text-ink-muted">
                  Add a contribution at checkout — 5,000, 10,000, 20,000 TZS or an amount you choose. It
                  goes to the project you pick, and you get the updates.
                </p>
                <div className="mt-8 flex flex-wrap gap-3">
                  <ButtonLink href="/trips">
                    Find a trip
                    <Icon.arrow />
                  </ButtonLink>
                  <ButtonLink href="/impact/dashboard" variant="secondary">
                    Impact dashboard
                  </ButtonLink>
                </div>
              </div>
              <div className="media relative min-h-56 lg:min-h-full">
                <Image
                  src="https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&h=1200&q=80"
                  alt="A busy street scene"
                  fill
                  sizes="(max-width: 1024px) 100vw, 40vw"
                  className="object-cover"
                />
              </div>
            </div>
          </Card>
        </div>
      </section>
    </PublicShell>
  );
}

function CategoryChip({ href, label, active }: { href: string; label: string; active: boolean }) {
  return (
    <Link
      href={href}
      className={cx(
        'inline-flex h-11 shrink-0 items-center rounded-[--radius-pill] border px-4 text-[0.875rem] font-semibold transition-all',
        active
          ? 'border-clay-500 bg-clay-500 text-white'
          : 'border-line-strong bg-white text-ink-soft hover:border-clay-400 hover:text-ink',
      )}
    >
      {label}
    </Link>
  );
}
